version: "3.9"

services:
  db:
    restart: always
    hostname: db
    build:
      context: .
      dockerfile: ./docker/postgres.Dockerfile
    env_file:
      - ./settings/db.env
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    env_file:
      - ./settings/redis.env
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 5s
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./data/redis:/data

  app:
    build:
      context: .
      dockerfile: ./docker/app.Dockerfile
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./settings/db.env
      - ./settings/app.env
      - ./settings/redis.env
    environment:
      POSTGRES_HOST: db
      REDIS_HOST: redis
    depends_on:
      db:
        condition: service_healthy

volumes:
  redis:
    driver: local

networks:
  default:
    driver: bridge
